name = "love-records-worker"
main = "src/index.ts"
compatibility_date = "2024-07-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "love-records-db"
database_id = "efe3d129-5402-4baa-9315-b53da6f31736"

# R2 Bucket
[[r2_buckets]]
binding = "R2"
bucket_name = "love-records-photos"

# Environment variables
[vars]
JWT_SECRET = "love-records-secret-2024-very-secure"
